# Generated by Django 5.1.1 on 2024-09-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodTitle', models.CharField(max_length=100)),
                ('prodPrice', models.FloatField()),
                ('prodDiscount', models.FloatField()),
                ('prodCategory', models.CharField(max_length=50)),
                ('prodDescription', models.TextField()),
                ('prodImage', models.CharField(max_length=300)),
            ],
        ),
    ]
