# Generated by Django 5.1.1 on 2024-09-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rename_address_order_custaddress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
